

export const config = {
  PORT:process.env.PORT,
  MONGO_URI:process.env.MONGO_URI,
  REFRESH_TOKEN_SECRET:process.env.REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_SECRET:process.env.ACCESS_TOKEN_SECRET,
  IMAGEKIT_PRIVATE_KEY:process.env.IMAGEKIT_PRIVATE_KEY,
  IMAGEKIT_PUBLIC_KEY:process.env.IMAGEKIT_PUBLIC_KEY,
  IMAGEKIT_ENDPOINT:process.env.IMAGEKIT_ENDPOINT,
}

